version: '3'

services:
  api:
    container_name: api
    image: api
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    entrypoint: ./start.sh
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - pg
      - kafka
    volumes:
      - ./src/backend/alembic/versions:/alembic/versions

  pg:
    container_name: pg
    image: postgres:latest
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - pg
    
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    ports:
      - "9091:9091"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9091,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9091
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CLUSTER_ID: i7DivAfCTKC58UAp_FIfcQ
    volumes:
      - ./src/kafka_data:/bitnami/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9091"
    depends_on:
      - kafka

  tg:
    container_name: tg
    image: tg
    build:
      context: ./src/telegram_channel
      dockerfile: Dockerfile
    entrypoint: ./start.sh
    env_file:
      - .env
    depends_on:
      - pg
      - kafka

  email:
    container_name: email
    image: email
    build:
      context: ./src/email_channel
      dockerfile: Dockerfile
    entrypoint: ./start.sh
    env_file:
      - .env
    depends_on:
      - pg
      - kafka
