# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AttractionEvents.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41ttractionEvents.proto\"\x89\x02\n\x0f\x41ttractionEvent\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x12\n\npartner_id\x18\x04 \x01(\t\x12!\n\x19link_to_attraction_domain\x18\x05 \x01(\t\x12\x13\n\x0bwork_status\x18\x06 \x01(\t\x12\n\n\x02id\x18\x07 \x01(\t\x12\'\n\x06\x61\x63tion\x18\x08 \x01(\x0e\x32\x17.AttractionEvent.Action\"B\n\x06\x41\x63tion\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x12\x11\n\rLICENSE_ADDED\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AttractionEvents_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ATTRACTIONEVENT._serialized_start=27
  _ATTRACTIONEVENT._serialized_end=292
  _ATTRACTIONEVENT_ACTION._serialized_start=226
  _ATTRACTIONEVENT_ACTION._serialized_end=292
# @@protoc_insertion_point(module_scope)
