# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubdivisionEvents.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17SubdivisionEvents.proto\"\xab\x02\n\x10SubdivisionEvent\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12-\n%link_to_subdivision_processing_domain\x18\x05 \x01(\t\x12\x13\n\x0bwork_status\x18\x06 \x01(\t\x12\n\n\x02id\x18\x07 \x01(\t\x12(\n\x06\x61\x63tion\x18\x08 \x01(\x0e\x32\x18.SubdivisionEvent.Action\"W\n\x06\x41\x63tion\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x12\x11\n\rLICENSE_ADDED\x10\x03\x12\x13\n\x0fLICENSE_EXPIRED\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SubdivisionEvents_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBDIVISIONEVENT._serialized_start=28
  _SUBDIVISIONEVENT._serialized_end=327
  _SUBDIVISIONEVENT_ACTION._serialized_start=240
  _SUBDIVISIONEVENT_ACTION._serialized_end=327
# @@protoc_insertion_point(module_scope)
