# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LicenseEvents.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13LicenseEvents.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x03\n\x0cLicenseEvent\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x16\n\x0esubdivision_id\x18\x05 \x01(\t\x12\x11\n\ttenant_id\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x16\n\x0e\x63ount_requests\x18\x08 \x01(\x05\x12-\n\tactivated\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\texpirated\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpiration\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02id\x18\r \x01(\t\x12$\n\x06\x61\x63tion\x18\x0e \x01(\x0e\x32\x14.LicenseEvent.Action\">\n\x06\x41\x63tion\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x12\r\n\tACTIVATED\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LicenseEvents_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LICENSEEVENT._serialized_start=57
  _LICENSEEVENT._serialized_end=523
  _LICENSEEVENT_ACTION._serialized_start=461
  _LICENSEEVENT_ACTION._serialized_end=523
# @@protoc_insertion_point(module_scope)
